=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

*_Note : 1 page max._*

Décrivez, en les citant via la bibliographie, les approches/produits
ressemblant à votre projet et les différences éventuelles. Illustrez
avec des images si besoin. Utilisez des renvois vers votre
bibliographie : « comme démontré dans [2], … »

On distingue divers types d’applications écologiques.

Celles qui donnent une liste d’actions positives réalisables au quotidien à 
l’image de WAG développée par WWF.

Celles qui encouragent les actions de groupe que ce soit par des défis à relever
en entreprise ou l’accès à une carte des personnes réalisant des actions 
quotidiennes bénéfiques à l’image de KOOM.

Celles qui proposent des choix de consommation responsables et les rétribue par 
un système de points échangeables contre des récompenses à l’image de ZEI. 

Green Guy est un réseau social et est donc orienté sur les actions de groupe 
(défis, rencontres de commerçants engagés). Il permet de sensibiliser 
l’utilisateur en lui distillant des informations et en l’informant des 
événements écologiques organisés.

Il se démarque des applications déjà existantes de par sa carte interactive 
performante où sont localisés tous les lieux qui sont engagés dans la cause 
écologique. Ses partenariats avec les communes permettent à l’application de 
contribuer à l’économie circulaire.


==== Exemples de citations

Les références bibliographiques sont regroupées dans le fichier `References.adoc`
à la racine du répertoire `rapport`.
On peut y faire référence dans toutes les sous parties du document.

On peut citer comme exemple l'article de Claude E. Shannon sur la
théorie de la communication <<RefShannon>>
ou, bien évidement, la vitrine des projets PACT <<VitrinePACT>>.

Voir <<TOTO,la référence>> très intéressante elle aussi.
