=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]


On distingue divers types d’applications écologiques.

Celles qui donnent une liste d’actions positives réalisables au quotidien à l’image de WAG développée par WWF.<<WAG>>
Celles qui encouragent les actions de groupe que ce soit par des défis à relever en entreprise ou l’accès à une carte des personnes réalisant des actions quotidiennes bénéfiques à l’image de KOOM.<<KOOM>>

Celles qui proposent des choix de consommation responsables et les rétribue par un système de points échangeables contre des récompenses à l’image de ZEI. <<ZEI>>

Celles qui mettent en lien des particuliers qui souhaitent donner des objets au lieu de les jeter avec d’autres qui souhaitent les récupérer à l’image de SmartCycle.<<SMARTCYCLE>>

Green Guy est un réseau social et est donc orienté sur les actions de groupe (défis, rencontres de commerçants engagés). Il permet de sensibiliser l’utilisateur en lui distillant des informations et en l’informant des événements écologiques organisés.

L'idée ici est de fusionner plusieurs fonctionnalités de ces diverses applications déjà existantes indépendemment les unes des autres.

En plus de cela, nous ajoutons un accès facile à  l'utilisateur à la carte et au fil d'actualité.
Nous souhaitons également insister sur les actions de groupe et enfin nouer des partenariats avec les communes afin d'élargir la communauté au maximum et de s'inscrire dans une optique d'économie circulaire.


