=== Scénarios d’usage
APPLICATION GREEN GUY 

==== Utilisateur 1

Sensibilisée aux enjeux du développement, durable, Alexandra souhaite consommer de manière plus responsable. D’ailleurs, ce midi elle a prévu d’aller au restaurant. Cela tombe bien, Green Guy lui propose une sélection d’adresses eco-friendly. Sur son chemin, elle découvre un canapé-lit jeté au milieu de la rue. Bizarre, les encombrants auraient dû passer la veille! Pas de problème, elle dégaine son téléphone, trouve l’appli et signale l’objet sur sa carte interactive. Il pourra ainsi profiter à un autre utilisateur ou même être retiré par les services municipaux si personne n’est intéressé! En revenant, elle cherche une fontaine d’eau car elle en a assez d’acheter des bouteilles en plastique. Encore une fois, Green Guy lui propose la source la plus proche, il y a même une épicerie vrac sur le chemin.Mais Green Guy c’est aussi une source d’événements à conscience écologique, un accès à la poubelle la plus proche via la localisation et des informations sur le recyclage, le compost...
Elle peut noter les lieux qu’elle visite par rapport à leur impact écologique, et utiliser les notes des autres utilisateurs pour décider des lieux qu’elle visite.


==== Utilisateur 2

Thomas est responsable de relations publiques de son entreprise. Pour partager l’impact positif sur l’environnement de son entreprise, il peut utiliser l’application pour créer des évènements et interagir avec la communauté Green Guy. Son utilisation est similaire à celle de Jean, qui appartient à une association orientée vers le développement durable et qui organise régulièrement des événements pour enrichir son association de nouveaux volontaires qui ont pu la découvrir grâce à Green Guy. Alexandra participe à l’un de ces évènements et rejoint un groupe avec lequel elle pourra communiquer grâce à la messagerie de Green Guy, et ajouter des amis.


==== Utilisateur 3

Marie travaille à la mairie de la ville. Ses services ont accès aux données de l’application, ce qui permet une meilleure communication entre les habitants et la municipalité. Par ailleurs, les données de la carte permettent aux services de propreté de réagir efficacement aux accumulations de déchets. Le portail Mairie propose une carte en direct qui propose un trajet optimisé aux éboueurs. 
Les bus de la ville, qui réalisent les mêmes trajets plusieurs fois par jour, sont équipés de caméras qui font le travail de reconnaissance de déchets et de cartographie en relation avec le serveur passivement, sans avoir à solliciter l’interaction d’un utilisateur de type 1. 
